### ISSUE TITLE
I can't find this paper. Could you please provide the download link of this paper?

### ISSUE THREAD

**Issue by MaQingya** [EscapeTheWind/Edge-Computing-and-Caching-Optimization-based-on-PPO-for-Task-Offloading-in-RSU-assisted-IoV#2]

**Comment by EscapeTheWind** [comment]
This article has been accepted but has not been officially published yet. It is still in the conference stage. You can add my WeChat to get the pdf version of the paper. WeChat ID: Neverthemore-
