### ISSUE TITLE
seeking papers

### ISSUE THREAD

**Issue by Peiho** [EscapeTheWind/Edge-Computing-and-Caching-Optimization-based-on-PPO-for-Task-Offloading-in-RSU-assisted-IoV#4]
Is there a paper for this project? If so, can you share it? Thank you very much for replying to this question.
Email: [liupeiho@126.com](mailto:liupeiho@126.com)

**Comment by EscapeTheWind** [comment]
Please check your e-mail.
I just send the pdf file to the address you gave me.
