### ISSUE TITLE
It seems that your article has not been published yet. Where can I get the pdf?

### ISSUE THREAD

**Issue by yc-whu** [EscapeTheWind/Edge-Computing-and-Caching-Optimization-based-on-PPO-for-Task-Offloading-in-RSU-assisted-IoV#5]
It seems that your article has not been published yet. Where can I get the pdf?
Edge Computing and Caching Optimization based on PPO for Task Offloading in RSU-assisted IoV

**Comment by EscapeTheWind** [comment]
You can contact me on WeChat to get the pdf version of the paper.
WeChat Account: Neverthemore-
