### ISSUE TITLE
Paper location?

### ISSUE THREAD

**Issue by Hum-many** [EscapeTheWind/Edge-Computing-and-Caching-Optimization-based-on-PPO-for-Task-Offloading-in-RSU-assisted-IoV#6]
I'd like to know where and how to find the paper related to this code.

**Comment by EscapeTheWind** [comment]
It hasn't been published yet.
You could add my WeChat: Neverthemore-
or you could contact me via e-mail 1303328276@qq.com,
I will send the paper to you.
