### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by ysyyyy1** [EscapeTheWind/Edge-Computing-and-Caching-Optimization-based-on-PPO-for-Task-Offloading-in-RSU-assisted-IoV#8]
May I ask for the DOI of the paper

**Comment by EscapeTheWind** [comment]
This article has been accepted but has not been officially published yet. It is still in the conference stage. You can add my WeChat to get the pdf version of the paper. WeChat ID: Neverthemore-

In case you're not a chinese developer and don't have a WeChat account, you can contact me via email: 1303328276@qq.com, and I'll send the paper to you.
